apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: widget-server-deployment
  namespace: widget

spec:
  replicas: 10
  revisionHistoryLimit: 5
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 20%
  #     maxUnavailable: 10%
  selector:
    matchLabels:
      app: widget-server
  strategy:
    #blueGreen:
    #  activeService: widget-server-svc
    #  previewService: widget-server-preview
    #  autoPromotionEnabled: false
    canary:
      stableService: widget-server-svc
      canaryService: widget-server-svc-preview
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 30s}
        - setWeight: 60
        - pause: {duration: 20s}
        - setWeight: 80
        - pause: {duration: 10s}
        - setWeight: 90
        - pause: {}
  template:
    metadata:
      labels:
        app: widget-server
    spec:
      containers:
        - name: widget-server
          image: danielrodriguess/widget-server:v4
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: widget-server-cm
            - secretRef:
                name: widget-server-secret
          ports:
            - containerPort: 3333
          startupProbe:
            httpGet:
              path: /health
              port: 3333
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 15
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3333
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 15
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 3333
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 15
            initialDelaySeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi