apiVersion: v1
kind: Secret

metadata:
  name: widget-server-secret
  namespace: widget

type: Opaque

data:
  CLOUDFLARE_ACCESS_KEY_ID: "Iw=="
  CLOUDFLARE_SECRET_ACCESS_KEY: "Iw=="
  CLOUDFLARE_ACCOUNT_ID: "Iw=="