apiVersion: v1
kind: Service

metadata:
  name: widget-server-svc
  namespace: widget

spec:
  type: ClusterIP
  selector:
    app: widget-server
  ports:
    - port: 80
      targetPort: 3333

---
apiVersion: v1
kind: Service

metadata:
  name: widget-server-preview
  namespace: widget

spec:
  type: ClusterIP
  selector:
    app: widget-server
  ports:
    - port: 80
      targetPort: 3333